// src/components/sheets/ApiKeySheet.tsx
import { useEffect, useState } from 'react'
import { useAppStore } from '../../store'
import { closeSheet } from '../../lib/sheets'
import { showToast } from '../../lib/toast'
import Sheet from '../Sheet'

export default function ApiKeySheet() {
  const open = useAppStore((s) => s.openSheetId === 'apikey')
  const [key, setKey] = useState('')

  useEffect(() => {
    if (open) setKey('')
  }, [open])

  function handleSave() {
    const trimmed = key.trim()
    if (!trimmed) return
    localStorage.setItem('tracker-anthropic-key', trimmed)
    showToast('API key saved')
    closeSheet()
  }

  return (
    <Sheet open={open} title="Set up Sonnet 4.6">
      <p className="setup-note">
        Paste your <a href="https://console.anthropic.com/settings/keys" target="_blank" rel="noopener">Anthropic API key</a>.
        Stored locally — never sent anywhere except Anthropic's API.
      </p>
      <div className="form-field">
        <label className="form-label" htmlFor="apikey-input">API key</label>
        <input className="form-input" id="apikey-input" type="password" placeholder="sk-ant-..." autoComplete="off" value={key} onChange={(e) => setKey(e.target.value)} />
      </div>
      <button className="btn-primary" onClick={handleSave}>Save</button>
    </Sheet>
  )
}

// src/components/sheets/ApiKeySheet.svelte
<script>
  import { closeSheets, showToast } from '../../lib/ui.js'
  import Sheet from './Sheet.svelte'

  let key = ''

  function save() {
    if (!key.trim()) return
    localStorage.setItem('tracker-anthropic-key', key.trim())
    closeSheets()
    showToast('✅ API key saved')
  }
</script>

<Sheet id="apikey-sheet">
  <svelte:fragment slot="title">Set up Claude AI</svelte:fragment>

  <p class="setup-note">
    Paste your <a href="https://console.anthropic.com/settings/keys" target="_blank">Anthropic API key</a>.
    Stored locally — never sent anywhere except Anthropic's API.
  </p>

  <div class="form-field">
    <label class="form-label" for="apikey-svelte-input">API key</label>
    <input class="form-input" id="apikey-svelte-input" type="password" placeholder="sk-ant-..." autocomplete="off" bind:value={key} />
  </div>

  <button class="btn-primary" on:click={save}>Save</button>
</Sheet>
